# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

install:
  - pip install -e .
  - pip install pytest pytest-cov codecov

script:
  - pytest --cov

after_success:
  - codecov
