# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
  - "pypy"

install:
  - pip install -e .
  - pip install pytest pytest-cov pytest-console-scripts codecov compressed_rtf

script:
  - pytest --cov

after_success:
  - codecov
